#!/bin/bash

# ========================================
# COMANDOS ÚTEIS - GESTÃO DO SISTEMA
# ========================================

DOMAIN="gestor.emmvmfc.com.br"
APP_DIR="/var/www/html/cardapio"

echo "🔧 COMANDOS ÚTEIS PARA GESTÃO DO SISTEMA"
echo "========================================"
echo ""

echo "📊 MONITORAMENTO:"
echo "• Ver status dos serviços:"
echo "  systemctl status nginx php8.2-fpm mysql"
echo ""
echo "• Ver logs em tempo real:"
echo "  tail -f /var/log/gestao-alimentar/monitor.log"
echo "  tail -f $APP_DIR/storage/logs/laravel.log"
echo "  tail -f /var/log/nginx/gestao-alimentar.error.log"
echo ""
echo "• Ver uso de recursos:"
echo "  htop"
echo "  df -h"
echo "  free -h"
echo ""

echo "🔄 MANUTENÇÃO:"
echo "• Reiniciar serviços:"
echo "  systemctl restart nginx"
echo "  systemctl restart php8.2-fpm"
echo "  systemctl restart mysql"
echo ""
echo "• Limpar cache Laravel:"
echo "  cd $APP_DIR"
echo "  php artisan cache:clear"
echo "  php artisan config:cache"
echo "  php artisan route:cache"
echo "  php artisan view:cache"
echo ""
echo "• Backup manual:"
echo "  /usr/local/bin/backup-gestao.sh"
echo ""

echo "🔒 SSL:"
echo "• Ver certificados:"
echo "  certbot certificates"
echo ""
echo "• Renovar SSL:"
echo "  certbot renew"
echo ""
echo "• Testar renovação:"
echo "  certbot renew --dry-run"
echo ""

echo "🗄️ BANCO DE DADOS:"
echo "• Conectar ao MySQL:"
echo "  mysql -u gestao_user -p gestao_alimentar"
echo ""
echo "• Backup do banco:"
echo "  mysqldump -u gestao_user -p gestao_alimentar > backup.sql"
echo ""
echo "• Restaurar banco:"
echo "  mysql -u gestao_user -p gestao_alimentar < backup.sql"
echo ""

echo "🔥 FIREWALL:"
echo "• Ver status:"
echo "  ufw status"
echo ""
echo "• Ver tentativas bloqueadas:"
echo "  fail2ban-client status"
echo "  fail2ban-client status sshd"
echo ""

echo "📁 ARQUIVOS IMPORTANTES:"
echo "• Configuração Nginx: /etc/nginx/sites-available/gestao-alimentar"
echo "• Configuração PHP: /etc/php/8.2/fpm/conf.d/99-gestao-alimentar.ini"
echo "• Logs do sistema: /var/log/gestao-alimentar/"
echo "• Backups: /backup/gestao-alimentar/"
echo ""

echo "🚨 EMERGÊNCIA:"
echo "• Modo manutenção:"
echo "  cd $APP_DIR && php artisan down"
echo "  cd $APP_DIR && php artisan up"
echo ""
echo "• Verificar erros:"
echo "  nginx -t"
echo "  php -m | grep mysql"
echo "  cd $APP_DIR && php artisan migrate:status"
echo ""
