#!/bin/bash
# Comandos para corrigir o problema do composer

echo "🔧 COMANDOS DE CORREÇÃO PASSO A PASSO"
echo "===================================="

echo ""
echo "PASSO 1: Encontrar a pasta correta"
echo "-----------------------------------"
echo "Execute este comando para encontrar onde está o arquivo artisan:"
echo ""
echo "find /home/catalogonet -name 'artisan' -type f 2>/dev/null"
echo ""

echo "PASSO 2: Navegar para a pasta correta"
echo "------------------------------------"
echo "Depois de encontrar, navegue para a pasta:"
echo ""
echo "cd /caminho/para/pasta/encontrada"
echo ""

echo "PASSO 3: Verificar estrutura"
echo "---------------------------"
echo "Verifique se está na pasta correta:"
echo ""
echo "ls -la"
echo "# Deve mostrar: artisan, composer.json, app/, config/, etc."
echo ""

echo "PASSO 4: Instalar dependências"
echo "-----------------------------"
echo "Instale as dependências sem executar scripts:"
echo ""
echo "composer install --no-scripts --no-dev"
echo ""

echo "PASSO 5: Gerar autoload"
echo "----------------------"
echo "Gere o autoload do composer:"
echo ""
echo "composer dump-autoload"
echo ""

echo "PASSO 6: Corrigir permissões"
echo "---------------------------"
echo "Corrija as permissões dos arquivos:"
echo ""
echo "chmod +x artisan"
echo "chmod -R 755 storage/"
echo "chmod -R 755 bootstrap/cache/"
echo ""

echo "PASSO 7: Executar comandos Laravel"
echo "---------------------------------"
echo "Execute os comandos do Laravel:"
echo ""
echo "php artisan key:generate"
echo "php artisan config:cache"
echo "php artisan route:cache"
echo ""

echo "PASSO 8: Testar instalação"
echo "-------------------------"
echo "Teste se tudo está funcionando:"
echo ""
echo "php artisan --version"
echo "php artisan list"
