#!/bin/bash
# Soluções para problemas do composer

echo "🚀 SOLUÇÕES PARA COMPOSER INSTALL"
echo "================================="

echo "SOLUÇÃO 1: Navegar para pasta correta"
echo "-------------------------------------"
echo "# Encontrar a pasta do projeto Laravel:"
echo "find /home/catalogonet -name 'artisan' -type f 2>/dev/null"
echo ""
echo "# Navegar para a pasta encontrada:"
echo "cd /caminho/para/pasta/do/projeto"
echo ""

echo "SOLUÇÃO 2: Verificar e corrigir estrutura"
echo "----------------------------------------"
echo "# Listar conteúdo da pasta atual:"
echo "ls -la"
echo ""
echo "# Se estiver em gme.emmvmfc.com.br, verificar subpastas:"
echo "ls -la */"
echo ""

echo "SOLUÇÃO 3: Criar arquivo artisan se não existir"
echo "----------------------------------------------"
echo "# Verificar se existe artisan:"
echo "ls -la artisan"
echo ""
echo "# Se não existir, criar:"
echo "touch artisan"
echo "chmod +x artisan"
echo ""

echo "SOLUÇÃO 4: Reinstalar dependências"
echo "---------------------------------"
echo "# Remover vendor e reinstalar:"
echo "rm -rf vendor/"
echo "rm -f composer.lock"
echo "composer install --no-scripts"
echo "composer dump-autoload"
echo ""

echo "SOLUÇÃO 5: Instalar sem scripts"
echo "------------------------------"
echo "# Instalar sem executar scripts:"
echo "composer install --no-scripts --no-dev"
echo ""
echo "# Depois executar scripts manualmente:"
echo "composer dump-autoload"
echo ""

echo "SOLUÇÃO 6: Verificar permissões"
echo "------------------------------"
echo "# Verificar permissões da pasta:"
echo "ls -la"
echo ""
echo "# Corrigir permissões se necessário:"
echo "chmod -R 755 ."
echo "chmod +x artisan"
